In [1]:
import torch

In [2]:
x=torch.rand(2,3)

In [3]:
x

tensor([[0.9202, 0.6130, 0.8820],
        [0.9634, 0.0843, 0.9968]])

In [4]:
x=torch.rand(3,4)

In [5]:
x

tensor([[0.4802, 0.2339, 0.1596, 0.5254],
        [0.0500, 0.7058, 0.5176, 0.7672],
        [0.0808, 0.1427, 0.7738, 0.8604]])

In [6]:
x=torch.zeros(2,3)

In [7]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
x=torch.ones(2,3,4)

In [9]:
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
x.size()

torch.Size([2, 3, 4])

In [11]:
x.shape

torch.Size([2, 3, 4])

In [12]:
x.size(0)

2

Tensor的最基本数据类型：  
32位浮点型：torch.float32  
64位浮点型：torch.float64  
16位整型：torch.int16  
32位整型：torch.int32  
64位整型：torch.int64  

In [13]:
x=torch.tensor([6,2],dtype=torch.float32)

In [14]:
x

tensor([6., 2.])

In [15]:
x.type()

'torch.FloatTensor'

In [16]:
x.type(torch.int64)

tensor([6, 2])

# Tensor与numpy之间的转变

In [17]:
import numpy as np

In [18]:
a=np.random.randn(2,3)

In [19]:
a

array([[ 0.20150154, -1.86180661,  0.81464775],
       [-0.24765844,  1.09538054, -0.11878747]])

In [20]:
x1=torch.from_numpy(a)

In [21]:
x1

tensor([[ 0.2015, -1.8618,  0.8146],
        [-0.2477,  1.0954, -0.1188]], dtype=torch.float64)

In [22]:
x1.numpy()#未改变x1本身的值只是做了运算

array([[ 0.20150154, -1.86180661,  0.81464775],
       [-0.24765844,  1.09538054, -0.11878747]])

# 张量的运算

In [23]:
x1

tensor([[ 0.2015, -1.8618,  0.8146],
        [-0.2477,  1.0954, -0.1188]], dtype=torch.float64)

In [24]:
x2=torch.rand(2,3)#不是x2=torch.randn(2,3)

In [25]:
x2

tensor([[0.0930, 0.4234, 0.6048],
        [0.6220, 0.1666, 0.4000]])

In [28]:
print(torch.__version__)

1.2.0


In [29]:
x1 + x2

RuntimeError: expected device cpu and dtype Double but got device cpu and dtype Float

In [30]:
x1 + 3

tensor([[3.2015, 1.1382, 3.8146],
        [2.7523, 4.0954, 2.8812]], dtype=torch.float64)

In [31]:
x1.add(x2)

RuntimeError: expected device cpu and dtype Double but got device cpu and dtype Float

In [32]:
x1.add_(x2)

RuntimeError: expected device cpu and dtype Double but got device cpu and dtype Float

In [33]:
x1

tensor([[ 0.2015, -1.8618,  0.8146],
        [-0.2477,  1.0954, -0.1188]], dtype=torch.float64)

In [34]:
x1.shape

torch.Size([2, 3])

In [35]:
x1.view(3,2)#类似于numpy中的reshape

tensor([[ 0.2015, -1.8618],
        [ 0.8146, -0.2477],
        [ 1.0954, -0.1188]], dtype=torch.float64)

In [36]:
x1.view(-1,1)#把数据展平

tensor([[ 0.2015],
        [-1.8618],
        [ 0.8146],
        [-0.2477],
        [ 1.0954],
        [-0.1188]], dtype=torch.float64)

In [37]:
x1.mean()

tensor(-0.0195, dtype=torch.float64)

In [38]:
x=x1.sum()

In [39]:
x

tensor(-0.1167, dtype=torch.float64)

In [40]:
x.item()#直接吧标量数值返回来

-0.11672267891334401

## 张量的自动微分

将Torch.Tensor属性.requires_grad设置为True  
pytorch将会开始跟踪对此张量的所有操作  
完成计算后，可以调用.backward()并计算所有的梯度  
该梯度所有属性将会累加到.grad属性当中

In [45]:
x=torch.ones(2,2,requires_grad=True)

In [46]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [48]:
x.requires_grad

True

In [49]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [50]:
x.grad

In [51]:
x.grad_fn

In [52]:
y=x + 2

In [53]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [54]:
y.grad_fn

In [55]:
z=y*y +3

In [56]:
out=z.mean()

In [57]:
out

tensor(12., grad_fn=<MeanBackward0>)

In [58]:
out.backward()

out=f(x)  
d out/dx

In [59]:
x.grad

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])

In [60]:
x.data

tensor([[1., 1.],
        [1., 1.]])

包含在以下语句时，不会跟踪tensor后面的计算；  
一般在验证集测试的时候我们会将测试数据放在以下语句当中

In [61]:
with torch.no_grad():
    print((x**x).requires_grad)

False


In [62]:
(x**x).requires_grad

True

In [63]:
y =x.detach()

In [64]:
y

tensor([[1., 1.],
        [1., 1.]])

In [66]:
y.requires_grad

False

In [71]:
a=torch.tensor([3,2],dtype=torch.float32)

In [72]:
a

tensor([3., 2.])

In [73]:
a.requires_grad

False

In [74]:
a.requires_grad_(True)

tensor([3., 2.], requires_grad=True)

In [75]:
a.requires_grad

True